export const SEQUELIZE = 'SEQUELIZE';
export const USERS_REPOSITORY = 'USERS_REPOSITORY';
export const FRIENDS_REPOSITORY = 'FRIENDS_REPOSITORY';
export const FRIEND_REQUESTS_REPOSITORY = 'FRIEND_REQUESTS_REPOSITORY';
export const CONVERSATION_REPOSITORY = 'CONVERSATION_REPOSITORY';
